[collection_workflow]
data_collection_tool = """  """
data_collection_year = """  """
feature_extraction_tool_info = """ Tool that converts dataset to feature dataset. If any. """
feature_extraction_tool = """  """
feature_extraction_tool_description = """  """
capture_config_parameters_info = """ specific parameters that were used to capture dataset or feature dataset """
capture_config_parameters = """  """
real_dataset_info = """ Source of the dataset. E.g., real environment, testbed or generated. """
real_dataset = """  """
annotation_info = """ Description of the dataset annotation. E.g., manual, automatic """
annotation = """  """

[generic_info]
classes = """ 101 """
features = """ 133 """
f1-score_info = """ F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM] """
f1-score = """ 0.8132164975149339 """
performance_metric_info = """ Perfomance metric defined by the author. Please define full specification e.g., F1-weighted """
performance_metric_name = """  """
performance_metric_value = """  """
label_info = """ Name of the field with label. In case this is unsupervised dataset, type None """
label = """  """
known_issues_info = """ Description of indentified issues in the dataset """
known_issues = """   """
key_observations_info = """ List of known errors, drifts, limits, ... of the dataset """
key_observations = """  *  The dataset has 0 small classes, 9332 duplicated samples, 0 nan value """
dataset_organization_info = """ Structure of the dataset. E.g., per day, per capture, per device """
dataset_organization = """  """
dataset_organization_description_info = """ Description of the content of the organization. Is there any metadata? """
dataset_organization_description = """   """
dataset_documentation_info = """ How to get started with the dataset. Ideally add example notebook. """
dataset_documentation = """   """
used_dataset_info = """ Script to get dataset for provided analysis """
used_dataset = """ get-dataset.py """
dataset_application_info = """ Where the dataset has been already applied. """
dataset_application = """   """
per_class_data = """{
  "62": "11409",
  "66": "11185",
  "59": "11013",
  "41": "10242",
  "55": "9592",
  "100": "8737",
  "50": "8310",
  "29": "7598",
  "28": "7536",
  "91": "6709",
  "49": "6370",
  "32": "6364",
  "17": "5727",
  "57": "5129",
  "89": "5113",
  "19": "4768",
  "61": "4169",
  "42": "2951",
  "75": "2902",
  "26": "2621",
  "5": "2515",
  "14": "2457",
  "68": "1990",
  "43": "1906",
  "60": "1884",
  "13": "1771",
  "79": "1550",
  "44": "1418",
  "47": "1302",
  "30": "1198",
  "27": "835",
  "36": "832",
  "76": "765",
  "52": "693",
  "48": "646",
  "31": "612",
  "78": "587",
  "82": "580",
  "39": "572",
  "53": "569",
  "98": "556",
  "93": "547",
  "4": "515",
  "12": "494",
  "54": "473",
  "67": "472",
  "56": "468",
  "3": "461",
  "11": "456",
  "65": "434",
  "88": "430",
  "99": "430",
  "15": "424",
  "97": "375",
  "92": "362",
  "33": "359",
  "22": "341",
  "45": "314",
  "96": "222",
  "70": "219",
  "64": "208",
  "72": "197",
  "58": "190",
  "20": "188",
  "37": "170",
  "18": "169",
  "46": "165",
  "73": "142",
  "90": "140",
  "35": "133",
  "10": "128",
  "8": "109",
  "94": "107",
  "21": "105",
  "85": "101",
  "25": "93",
  "38": "90",
  "81": "90",
  "87": "90",
  "51": "84",
  "77": "81",
  "63": "80",
  "40": "69",
  "74": "67",
  "24": "57",
  "9": "56",
  "0": "52",
  "7": "41",
  "80": "40",
  "86": "39",
  "84": "36",
  "83": "35",
  "16": "31",
  "1": "30",
  "2": "17",
  "34": "17",
  "6": "16",
  "69": "16",
  "95": "15",
  "23": "14",
  "71": "13"
}"""
per_feature_data = """{
  "IPT_1": "",
  "IPT_2": "",
  "IPT_3": "",
  "IPT_4": "",
  "IPT_5": "",
  "IPT_6": "",
  "IPT_7": "",
  "IPT_8": "",
  "IPT_9": "",
  "IPT_10": "",
  "IPT_11": "",
  "IPT_12": "",
  "IPT_13": "",
  "IPT_14": "",
  "IPT_15": "",
  "IPT_16": "",
  "IPT_17": "",
  "IPT_18": "",
  "IPT_19": "",
  "IPT_20": "",
  "IPT_21": "",
  "IPT_22": "",
  "IPT_23": "",
  "IPT_24": "",
  "IPT_25": "",
  "IPT_26": "",
  "IPT_27": "",
  "IPT_28": "",
  "IPT_29": "",
  "IPT_30": "",
  "DIR_1": "",
  "DIR_2": "",
  "DIR_3": "",
  "DIR_4": "",
  "DIR_5": "",
  "DIR_6": "",
  "DIR_7": "",
  "DIR_8": "",
  "DIR_9": "",
  "DIR_10": "",
  "DIR_11": "",
  "DIR_12": "",
  "DIR_13": "",
  "DIR_14": "",
  "DIR_15": "",
  "DIR_16": "",
  "DIR_17": "",
  "DIR_18": "",
  "DIR_19": "",
  "DIR_20": "",
  "DIR_21": "",
  "DIR_22": "",
  "DIR_23": "",
  "DIR_24": "",
  "DIR_25": "",
  "DIR_26": "",
  "DIR_27": "",
  "DIR_28": "",
  "DIR_29": "",
  "DIR_30": "",
  "SIZE_1": "",
  "SIZE_2": "",
  "SIZE_3": "",
  "SIZE_4": "",
  "SIZE_5": "",
  "SIZE_6": "",
  "SIZE_7": "",
  "SIZE_8": "",
  "SIZE_9": "",
  "SIZE_10": "",
  "SIZE_11": "",
  "SIZE_12": "",
  "SIZE_13": "",
  "SIZE_14": "",
  "SIZE_15": "",
  "SIZE_16": "",
  "SIZE_17": "",
  "SIZE_18": "",
  "SIZE_19": "",
  "SIZE_20": "",
  "SIZE_21": "",
  "SIZE_22": "",
  "SIZE_23": "",
  "SIZE_24": "",
  "SIZE_25": "",
  "SIZE_26": "",
  "SIZE_27": "",
  "SIZE_28": "",
  "SIZE_29": "",
  "SIZE_30": "",
  "BYTES": "",
  "BYTES_REV": "",
  "PACKETS": "",
  "PACKETS_REV": "",
  "PPI_LEN": "",
  "PPI_ROUNDTRIPS": "",
  "PPI_DURATION": "",
  "DURATION": "",
  "FEND_IDLE": "",
  "FEND_ACTIVE": "",
  "FEND_OTHER": "",
  "PSIZE_BIN1": "",
  "PSIZE_BIN2": "",
  "PSIZE_BIN3": "",
  "PSIZE_BIN4": "",
  "PSIZE_BIN5": "",
  "PSIZE_BIN6": "",
  "PSIZE_BIN7": "",
  "PSIZE_BIN8": "",
  "PSIZE_BIN1_REV": "",
  "PSIZE_BIN2_REV": "",
  "PSIZE_BIN3_REV": "",
  "PSIZE_BIN4_REV": "",
  "PSIZE_BIN5_REV": "",
  "PSIZE_BIN6_REV": "",
  "PSIZE_BIN7_REV": "",
  "PSIZE_BIN8_REV": "",
  "IPT_BIN1": "",
  "IPT_BIN2": "",
  "IPT_BIN3": "",
  "IPT_BIN4": "",
  "IPT_BIN5": "",
  "IPT_BIN6": "",
  "IPT_BIN7": "",
  "IPT_BIN8": "",
  "IPT_BIN1_REV": "",
  "IPT_BIN2_REV": "",
  "IPT_BIN3_REV": "",
  "IPT_BIN4_REV": "",
  "IPT_BIN5_REV": "",
  "IPT_BIN6_REV": "",
  "IPT_BIN7_REV": "",
  "IPT_BIN8_REV": "",
  "APP": ""
}"""

[dataset_drift_analysis]

[advanced_metrics]
description = """  """
perqoda_permutation_slope = """ 0.7787974498087595 """
p_value_status = """ Good """
redundancy = """ 0.2421875 """
similarity = """ 1.5729870138716484 """
advanced_metrics_workflow = """ dataset-metrics.json """

[dataset_comparison]
description = """ ML model comparison for this dataset """
use_case = """   """
similar_dataset = """   """
