[collection_workflow]
data_collection_tool = """  """
data_collection_year = """  """
feature_extraction_tool_info = """ Tool that converts dataset to feature dataset. If any. """
feature_extraction_tool = """  """
feature_extraction_tool_description = """  """
capture_config_parameters_info = """ specific parameters that were used to capture dataset or feature dataset """
capture_config_parameters = """  """
real_dataset_info = """ Source of the dataset. E.g., real environment, testbed or generated. """
real_dataset = """  """
annotation_info = """ Description of the dataset annotation. E.g., manual, automatic """
annotation = """  """

[generic_info]
classes = """ 101 """
features = """ 134 """
f1-score_info = """ F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM] """
f1-score = """  """
performance_metric_info = """ Perfomance metric defined by the author. Please define full specification e.g., F1-weighted """
performance_metric_name = """  """
performance_metric_value = """  """
label_info = """ Name of the field with label. In case this is unsupervised dataset, type None """
label = """  """
known_issues_info = """ Description of indentified issues in the dataset """
known_issues = """   """
key_observations_info = """ List of known errors, drifts, limits, ... of the dataset """
key_observations = """   The dataset has 0 small classes, 32764 duplicated samples, 0 nan value """
dataset_organization_info = """ Structure of the dataset. E.g., per day, per capture, per device """
dataset_organization = """  """
dataset_organization_description_info = """ Description of the content of the organization. Is there any metadata? """
dataset_organization_description = """   """
dataset_documentation_info = """ How to get started with the dataset. Ideally add example notebook. """
dataset_documentation = """   """
used_dataset_info = """ Script to get dataset for provided analysis """
used_dataset = """ get-dataset.py """
dataset_application_info = """ Where the dataset has been already applied. """
dataset_application = """   """
per_class_data = """{
  "62": "51486",
  "59": "47320",
  "41": "46773",
  "55": "42090",
  "50": "37624",
  "100": "37354",
  "66": "36094",
  "91": "30837",
  "49": "28581",
  "29": "25367",
  "28": "24947",
  "57": "23050",
  "17": "21785",
  "32": "21078",
  "19": "20869",
  "89": "20248",
  "61": "19027",
  "42": "13634",
  "75": "9382",
  "5": "8240",
  "43": "8135",
  "26": "8105",
  "60": "7922",
  "14": "7288",
  "13": "6464",
  "44": "6350",
  "68": "6021",
  "79": "5665",
  "47": "5325",
  "30": "4051",
  "52": "3210",
  "36": "3172",
  "48": "2634",
  "53": "2501",
  "82": "2298",
  "76": "2264",
  "67": "2227",
  "98": "2088",
  "93": "2088",
  "54": "2045",
  "27": "2029",
  "56": "1940",
  "88": "1909",
  "12": "1901",
  "78": "1892",
  "4": "1853",
  "33": "1670",
  "39": "1667",
  "15": "1655",
  "3": "1650",
  "11": "1591",
  "97": "1565",
  "99": "1558",
  "65": "1285",
  "31": "1253",
  "92": "1183",
  "96": "1174",
  "22": "1154",
  "45": "1148",
  "18": "1080",
  "58": "866",
  "70": "756",
  "64": "730",
  "72": "618",
  "73": "575",
  "90": "549",
  "37": "527",
  "20": "521",
  "10": "518",
  "46": "493",
  "25": "483",
  "38": "433",
  "8": "424",
  "77": "420",
  "85": "415",
  "51": "396",
  "35": "385",
  "21": "374",
  "94": "372",
  "40": "323",
  "87": "295",
  "81": "282",
  "63": "269",
  "9": "238",
  "74": "217",
  "24": "199",
  "0": "162",
  "86": "152",
  "1": "144",
  "16": "136",
  "84": "134",
  "80": "132",
  "7": "122",
  "69": "100",
  "83": "94",
  "95": "69",
  "23": "65",
  "34": "63",
  "71": "60",
  "2": "54",
  "6": "39"
}"""
per_feature_data = """{
  "IPT_1": "",
  "IPT_2": "",
  "IPT_3": "",
  "IPT_4": "",
  "IPT_5": "",
  "IPT_6": "",
  "IPT_7": "",
  "IPT_8": "",
  "IPT_9": "",
  "IPT_10": "",
  "IPT_11": "",
  "IPT_12": "",
  "IPT_13": "",
  "IPT_14": "",
  "IPT_15": "",
  "IPT_16": "",
  "IPT_17": "",
  "IPT_18": "",
  "IPT_19": "",
  "IPT_20": "",
  "IPT_21": "",
  "IPT_22": "",
  "IPT_23": "",
  "IPT_24": "",
  "IPT_25": "",
  "IPT_26": "",
  "IPT_27": "",
  "IPT_28": "",
  "IPT_29": "",
  "IPT_30": "",
  "DIR_1": "",
  "DIR_2": "",
  "DIR_3": "",
  "DIR_4": "",
  "DIR_5": "",
  "DIR_6": "",
  "DIR_7": "",
  "DIR_8": "",
  "DIR_9": "",
  "DIR_10": "",
  "DIR_11": "",
  "DIR_12": "",
  "DIR_13": "",
  "DIR_14": "",
  "DIR_15": "",
  "DIR_16": "",
  "DIR_17": "",
  "DIR_18": "",
  "DIR_19": "",
  "DIR_20": "",
  "DIR_21": "",
  "DIR_22": "",
  "DIR_23": "",
  "DIR_24": "",
  "DIR_25": "",
  "DIR_26": "",
  "DIR_27": "",
  "DIR_28": "",
  "DIR_29": "",
  "DIR_30": "",
  "SIZE_1": "",
  "SIZE_2": "",
  "SIZE_3": "",
  "SIZE_4": "",
  "SIZE_5": "",
  "SIZE_6": "",
  "SIZE_7": "",
  "SIZE_8": "",
  "SIZE_9": "",
  "SIZE_10": "",
  "SIZE_11": "",
  "SIZE_12": "",
  "SIZE_13": "",
  "SIZE_14": "",
  "SIZE_15": "",
  "SIZE_16": "",
  "SIZE_17": "",
  "SIZE_18": "",
  "SIZE_19": "",
  "SIZE_20": "",
  "SIZE_21": "",
  "SIZE_22": "",
  "SIZE_23": "",
  "SIZE_24": "",
  "SIZE_25": "",
  "SIZE_26": "",
  "SIZE_27": "",
  "SIZE_28": "",
  "SIZE_29": "",
  "SIZE_30": "",
  "BYTES": "",
  "BYTES_REV": "",
  "PACKETS": "",
  "PACKETS_REV": "",
  "PPI_LEN": "",
  "PPI_ROUNDTRIPS": "",
  "PPI_DURATION": "",
  "DURATION": "",
  "FEND_IDLE": "",
  "FEND_ACTIVE": "",
  "FEND_OTHER": "",
  "PSIZE_BIN1": "",
  "PSIZE_BIN2": "",
  "PSIZE_BIN3": "",
  "PSIZE_BIN4": "",
  "PSIZE_BIN5": "",
  "PSIZE_BIN6": "",
  "PSIZE_BIN7": "",
  "PSIZE_BIN8": "",
  "PSIZE_BIN1_REV": "",
  "PSIZE_BIN2_REV": "",
  "PSIZE_BIN3_REV": "",
  "PSIZE_BIN4_REV": "",
  "PSIZE_BIN5_REV": "",
  "PSIZE_BIN6_REV": "",
  "PSIZE_BIN7_REV": "",
  "PSIZE_BIN8_REV": "",
  "IPT_BIN1": "",
  "IPT_BIN2": "",
  "IPT_BIN3": "",
  "IPT_BIN4": "",
  "IPT_BIN5": "",
  "IPT_BIN6": "",
  "IPT_BIN7": "",
  "IPT_BIN8": "",
  "IPT_BIN1_REV": "",
  "IPT_BIN2_REV": "",
  "IPT_BIN3_REV": "",
  "IPT_BIN4_REV": "",
  "IPT_BIN5_REV": "",
  "IPT_BIN6_REV": "",
  "IPT_BIN7_REV": "",
  "IPT_BIN8_REV": "",
  "APP": "",
  "date": ""
}"""

[dataset_drift_analysis]

[advanced_metrics]
description = """  """
perqoda_permutation_slope = """  """
p_value_status = """  """
redundancy = """  """
similarity = """  """
advanced_metrics_workflow = """ dataset-metrics.json """

[dataset_comparison]
description = """ ML model comparison for this dataset """
use_case = """   """
similar_dataset = """   """
