acronym_info = "Short name of the dataset, which is used as the unique identifier. E.g., CESNET_TLS_Year22"
acronym = "CESNET-QUIC22"
acronym_aliases_info = "Additional alias for the Dataset Acronym (e.g. CESNET-TLS-Year22-XS). Used to filter the different subsection of the original dataset"
acronym_aliases = "CESNET-QUIC22"
title_info = "Full title of the dataset. E.g., CESNET-TLS-Year22"
title = ""
paper_title_info = "Full title of the original paper with the dataset"
paper_title = "CESNET-QUIC22: A large one-month QUIC network traffic dataset from backbone lines"
authors = "Jan Luxemburk, Karel Hynek, Tomáš Čejka, Andrej Lukačovič, Pavel Šiška"
description_info = "High-level description of the dataset. E.g., TLS capture from CESNET2 backbone network over one year (2022). The capture was done using high-speed monitoring probes at the perimeter of CESNET2 network. This dataset provides realistic characteristics of traffic originating from various web browsers, operating systems, mobile devices, desktop machines, and both HTTP/1.1 and HTTP/2 protocols."
description = "The dataset consists of network flows describing encrypted QUIC communications from CESNET backbone network. Flows were created using ipfixprobe flow exporter and are extended with packet metadata sequences, packet histograms, and with fields extracted from the QUIC Initial Packet, which is the first packet of the QUIC connection handshake. The extracted handshake fields are the Server Name Indication (SNI) domain, the used version of the QUIC protocol, and the user agent string that is available in a subset of QUIC communications."
format_info = "Dataset data format. E.g. json, csv, datazoo"
format = "csv"
doi_info = "DOI of this dataset"
doi = "https://doi.org/10.1016/j.dib.2023.108888"
origins_doi_info = "DOI of the original dataset"
origins_doi = ""
submitter = "Dominik Soukup <soukudom@fit.cvut.cz>"
tags_info = "Use tags to categorize the dataset (comma separated)"
tags = "network traffic classification, FETA"
url = "https://zenodo.org/records/7963302"
date_submitted = 2024-11-27T09:29:12.238000
versions = ""
analysis_status = "Completed"
files = ["get-dataset.py"]
label_name = "APP"
filename = ""

[collection_workflow]
data_collection_tool = "ipfixprobe"
data_collection_year = 2022
feature_extraction_tool_info = "Tool that converts dataset to feature dataset. If any."
feature_extraction_tool = "ipfixprobe PSTATS, QUIC, PHISTS"
feature_extraction_tool_description = "ipfix probe generates extended flow format based on used modules in the ipfixprobe. Per Packet Information (PPI) is flattended and used as single features."
capture_config_parameters_info = "specific parameters that were used to capture dataset or feature dataset"
capture_config_parameters = ""
real_dataset_info = "Source of the dataset. E.g., real environment, testbed or generated."
real_dataset = "yes, collected from CESNET3"
annotation_info = "Description of the dataset annotation. E.g., manual, automatic"
annotation = "Automatic based on SNI field from TLS header"

[generic_info]
capture_dates_info = "When was the dataset captured/generated"
capture_dates = "31.10.2022 - 27.11.2022"
classes = 102
features = "n/a"
f1-score_info = "F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM]"
f1-score = "n/a"
performance_metric_info = "Perfomance metric defined by the author. Please define full specification e.g., F1-weighted"
performance_metric_name = "n/a"
performance_metric_value = "n/a"
label_info = "Name of the field with label. In case this is unsupervised dataset, type None. In case of more labels use ',' to separate"
label = "APP,CATEGORY"
known_issues_info = """Description of indentified issues in the dataset"""
known_issues = """ """
key_observations_info = "List of known errors, drifts, limits, ... of the dataset"
key_observations = """
* Closed-world classification and evaluated trained classifiers on known classes
* LightGBM achieved the best accuracy at 80.87% [1][]
* When trained without handshake packets, multi-modal CNN improved to 87.96% accuracy [1][]
* Performance degraded over time, with a significant drop between weeks 2 and 3 (e.g., LightGBM accuracy dropped from 87.34% to 77.89%), Data drift caused Google certificate changes affecting patterns [1][]
* Models relying on handshake packets (first 8 packets) were more vulnerable to data drift [1][]
* Strong dependence on the 5th packet (likely containing server certificate) made models less robust [1][]
* Removing handshake packets improved stability but reduced recall scores [1][]
* One month duration may not be enough to evaluate long-term classifier behavior
* ML classification requires preprocessing
"""
dataset_organization_info = "Structure of the dataset. E.g., per day, per capture, per device"
dataset_organization = "per day"
dataset_organization_description_info = "Description of the content of the organization. Is there any metadata?"
dataset_organization_description = """Dataset is accessible via Datazoo framework which allows a convenient way to get data in python including various selection options. Iteration is possible per day as author claims."""
dataset_documentation_info = "How to get started with the dataset. Ideally add example notebook."
dataset_documentation = """
  This dataset is best available with the Datazoo framework. Full documentation with general Getting Started is available here https://cesnet.github.io/cesnet-datazoo/getting_started/. 
 """
used_dataset_info = "Script to get dataset for provided analysis"
used_dataset = "get-dataset.py"
dataset_application_info = "Where the dataset has been already applied. Format: id, doi, title, [cited/used,comment/comparison]"
dataset_application = """
* [1][] 10.23919/TMA58422.2023.10199052; Encrypted traffic classification: the QUIC case; [used][]
* [2][] https://doi.org/10.1145/3618257.3624820; Replication: Contrastive Learning and Data Augmentation in Traffic Classification Using a Flowpic Input Representation; [cited; Introduced eTC dataset as more advanced dataset. The datasets used in this paper are all smaller than CESNET-QUIC22, but they include more packet-level information.][]
* [3][] 10.1109/TNSM.2023.3287430; Benchmarking class incremental learning in deep learning traffic classification; [cited][]
* [4][] 10.1109/COMST.2024.3504955; A Survey on Explainable Artificial Intelligence for Internet Traffic Classification and Prediction, and Intrusion Detection; [cited][]
* [5][] 10.23919/TMA58422.2023.10198965; Many or Few Samples?: Comparing Transfer, Contrastive and Meta-Learning in Encrypted Traffic Classification; [cited][]
* [6][] 10.1109/ACCESS.2024.3469730; Early Traffic Classification With Encrypted ClientHello: A Multi-Country Study; [cited][]
* [7][] 10.1016/j.softx.2023.101506; Flow-models 2.0: Elephant flows modeling and detection with machine learnin; [cited][]
* [8][] 10.1038/s41597-024-04055-9; CESNET-TLS-Year22: A year-spanning TLS network traffic dataset from backbone lines; [cited; CESNET-TLS-Year22 is follow up dataset][]
* [9][] 10.1016/j.comnet.2024.110765; eXO: A commons-based community network Internet Service Provider, description and subscribers usage patterns; [cited][]
* [10][] 10.23919/CNSM59352.2023.10327823; Look at my Network: An Insight into the ISP Backbone Traffic; [cited][]
* [11][] 10.1016/j.comnet.2023.110147; NetTiSA: Extended IP flow with time-series features for universal bandwidth-constrained high-speed network traffic classification [cited]
* [12][] 10.1109/TNET.2024.3491840; Accelerating Network Features Deployment With Heterogeneous Platforms; [cited][]
* [13][] 10.1145/3630050.363017; DataZoo: Streamlining Traffic Classification Experiments; [cited][]
* [14][] 10.48550/arXiv.2410.06140; Estimating the Number of HTTP/3 Responses in QUIC Using Deep Learning; [cited; VisQUIC is a larger and more diverse dataset than CESNET-QUIC22. VisQUIC also includes SSL keys, which enable the decryption and detailed examination of encrypted traffic. However, VisQUIC does not include as many service labels as CESNET-QUIC22.][]
* [15][] 10.23919/TMA62044.2024.10559009; Towards Reusable Models in Traffic Classification [cited; The method requires full ppi information]
* [16][] 10.48550/arXiv.2410.03728; Exploring QUIC Dynamics: A Large-Scale Dataset for Encrypted Traffic Analysis; [cited; VisQUIC is a larger and more diverse dataset than CESNET-QUIC22. VisQUIC also includes SSL keys, which enable the decryption and detailed examination of encrypted traffic. However, VisQUIC does not include as many service labels as CESNET-QUIC22.][]
* [17][] 10.1109/LCN60385.2024.10639771; Is Deep Learning a Better Option than Random Forest for Encrypted Traffic Classification?; [used; Evalution of the proposed method][]
* [18][] 10.1109/ICCCNT56998.2023.10306767; Attention to Traffic: Network Traffic Classification using Attention-Based CNNs; [cited][]
* [19][] 10.1109/CCNC51664.2024.10454807; Hidden in Time, Revealed in Frequency: Spectral Features and Multiresolution Analysis for Encrypted Internet Traffic Classification; [Used for DWT-TC and STFT-TC methods;][]
* [20][] 10.1109/WCCCT60665.2024.10541553; QUIC Traffic Classification Based on Multi-Feature Fusion; [used; Evalution of the proposed method][]
"""
per_class_data = "n/a"
per_feature_data = """
{"ID": "Unique identifier",
"SRC_IP": "Source IP address",
"DST_IP": "Destination IP address",
"DST_ASN": "Destination Autonomous System number",
"SRC_PORT": "Source port",
"DST_PORT": "Destination port",
"PROTOCOL": "Transport protocol (UDP)",
"QUIC_VERSION": "QUIC protocol version",
"QUIC_SNI": "Server Name Indication domain",
"QUIC_USER_AGENT": "User agent string (if available)",
"TIME_FIRST": "Timestamp of the first packet",
"TIME_LAST": "Timestamp of the last packet",
"DURATION": "Duration of the flow in seconds",
"BYTES": "Number of transmitted bytes from client to server",
"BYTES_REV": "Number of transmitted bytes from server to client",
"PACKETS": "Number of packets transmitted from client to server",
"PACKETS_REV": "Number of packets transmitted from server to client",
"PPI": "Packet metadata sequence (inter-packet times, directions, sizes)",
"PPI_LEN": "Number of packets in the PPI sequence",
"PPI_DURATION": "Duration of the PPI sequence in seconds",
"PPI_ROUNDTRIPS": "Number of roundtrips in the PPI sequence",
"PHIST_SRC_SIZES": "Histogram of packet sizes from client to server",
"PHIST_DST_SIZES": "Histogram of packet sizes from server to client",
"PHIST_SRC_IPT": "Histogram of inter-packet times from client to server",
"PHIST_DST_IPT": "Histogram of inter-packet times from server to client",
"APP": "Web service label (or background traffic class)",
"CATEGORY": "Service category",
"FLOW_ENDREASON_IDLE": "Flow was terminated because it was idle",
"FLOW_ENDREASON_ACTIVE": "Flow was terminated because it reached the active timeout",
"FLOW_ENDREASON_OTHER": "Flow was terminated for other reasons"}
"""

[dataset_drift_analysis]
description = "not evaluated"

[advanced_metrics]
description = "not evaluated"

[dataset_comparison]
description = "ML model comparison for this dataset"
use_case = """
 * Encrypted traffic classification: the QUIC case, accuracy 89%, multi-modal CNN
 * Hidden in Time, Revealed in Frequency: Spectral Features and Multiresolution Analysis for Encrypted Internet Traffic Classification, accuracy 93%, F1-score 93.6%, random-forrest
 * Is Deep Learning a Better Option than Random Forest for Encrypted Traffic Classification?, accuracy 71.9%, F1-score 70.7%, random-forest
 * QUIC Traffic Classification Based on Multi-Feature Fusion, accuracy 99.95%; used SNI as categorycal feature 
 """
similar_dataset = """ 
* VisQUIC
* UCDAVIS19
* MIRAGE-19 
* MIRAGE-22
* UTMOBILENET21 
"""
# format: id, doi, title, [cited/used,comment/comparison]\n
# format: id, doi, title, [cited/used,comment/comparison]\n
