acronym_info = "Short name of the dataset, which is used as the unique identifier. E.g., CESNET_TLS_Year22"
acronym = "CESNET_TLS_Year22"
acronym_aliases_info = "Additional alias for the Dataset Acronym (e.g. CESNET-TLS-Year22-XS). Used to filter the different subsection of the original dataset"
acronym_aliases = "CESNET_TLS_Year22"
title_info = "Full title of the dataset. E.g., CESNET-TLS-Year22"
title = ""
paper_title_info = "Full title of the original paper with the dataset"
paper_title = "CESNET-TLS-Year22: A year-spanning TLS network traffic dataset from backbone lines"
authors = "Jan Luxemburk"
description_info = "High-level description of the dataset. E.g., TLS capture from CESNET2 backbone network over one year (2022). The capture was done using high-speed monitoring probes at the perimeter of CESNET2 network. This dataset provides realistic characteristics of traffic originating from various web browsers, operating systems, mobile devices, desktop machines, and both HTTP/1.1 and HTTP/2 protocols."
description = "TLS capture from CESNET2 backbone network over one year (2022). The capture was done using high-speed monitoring probes at the perimeter of CESNET2 network. This dataset provides realistic characteristics of traffic originating from various web browsers, operating systems, mobile devices, desktop machines, and both HTTP/1.1 and HTTP/2 protocols."
format = "datazoo"
doi_info = "DOI of this dataset"
doi = "https://doi.org/10.1038/s41597-024-03927-4"
origins_doi_info = "DOI of the original dataset"
origins_doi = ""
submitter = "Dominik Soukup <soukudom@cesnet.cz>"
tags_info = "Use tags to categorize the dataset (comma separated)"
tags = "network traffic classfication, FETA"
url = ""
date_submitted = 2024-11-14T08:54:25.010000
versions = ""
analysis_status = "Completed"
files = ["get-dataset.py"]
label_name = ""
filename = ""

[collection_workflow]
data_collection_tool = "ipfixprobe"
data_collection_year = 2022
feature_extraction_tool_info = "Tool that converts dataset to feature dataset. If any."
feature_extraction_tool = "ipfixprobe PSTATS, TLS, PHISTS"
feature_extraction_tool_description = "ipfix probe generates extended flow format based on used modules in the ipfixprobe. Per Packet Information (PPI) is flattended and used as single features."
capture_config_parameters_info = "specific parameters that were used to capture dataset or feature dataset"
capture_config_parameters = ""
real_dataset_info = "Source of the dataset. E.g., real environment, testbed or generated."
real_dataset = "yes, collected from CESNET3"
annotation_info = "Description of the dataset annotation. E.g., manual, automatic"
annotation = "Automatic based on SNI field from TLS header"

[generic_info]
capture_dates_info = "When was the dataset captured/generated"
capture_dates = "1.1.2022 - 31.12.2022"
classes = 180
features = "n/a"
f1-score_info = "F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM]"
f1-score = "n/a"
performance_metric_info = "Perfomance metric defined by the author. Please define full specification e.g., F1-weighted"
performance_metric_name = "n/a"
performance_metric_value = "n/a"
label_info = "Name of the field with label. In case this is unsupervised dataset, type None. In case of more labels use ',' to separate"
label = "APP,CATEGORY"
key_observations_info = "List of known errors, drifts, limits, ... of the dataset"
key_observations = """ 
* Closed-world classification and evaluated trained classifiers on known classes
* LightGBM achieved the best accuracy at 80.87% [1][] 
* When trained without handshake packets, multi-modal CNN improved to 87.96% accuracy [1][]
* Performance degraded over time, with a significant drop between weeks 2 and 3 (e.g., LightGBM accuracy dropped from 87.34% to 77.89%), Data drift caused Google certificate changes affecting patterns [1][]
* Models relying on handshake packets (first 8 packets) were more vulnerable to data drift [1][]
* Strong dependence on the 5th packet (likely containing server certificate) made models less robust [1][]
* Removing handshake packets improved stability but reduced recall scores [1][]
* One month duration may not be enough to evaluate long-term classifier behavior
* ML classification requires preprocessing
"""
dataset_organization_info = "Structure of the dataset. E.g., per day, per capture, per device"
dataset_organization = "per day"
dataset_organization_description_info = "Description of the content of the organization. Is there any metadata?"
dataset_organization_description = """Dataset is accessible via Datazoo framework which allows a convenient way to get data in python including various selection options. Iteration is possible per day as author claims."""
dataset_documentation_info = "How to get started with the dataset. Ideally add example notebook."
dataset_documentation = """
  This dataset is best available with the Datazoo framework. Full documentation with general Getting Started is available here https://cesnet.github.io/cesnet-datazoo/getting_started/. 
 """
used_dataset_info = "Script to get dataset for provided analysis"
used_dataset = "get-dataset.py"
dataset_application_info = "Where the dataset has been already applied. Format: id, doi, title, [cited/used,comment/comparison]"
dataset_application = """
 * [1][] 10.23919/CNSM62983.2024.10814630; MFWDD: Model-based Feature Weight Drift Detection Showcased on TLS and QUIC Traffic; [used; Validation of new method for drift detection][]
 * [2][] https://doi.org/10.1016/j.comnet.2025.111283; MFSI: Multi-flow based service identification for encrypted network traffic; [cited][]
 """

per_class_data = "n/a"
per_feature_data = " {\"ID\": \"Unique identifier\",\n \"SRC_IP\": \"Source IP address\",\n \"DST_IP\": \"Destination IP address\",\n \"DST_ASN\": \"Destination Autonomous System number\",\n \"SRC_PORT\": \"Source port\",\n \"DST_PORT\": \"Destination port\",\n \"PROTOCOL\": \"Transport protocol (UDP)\",\n \"QUIC_VERSION\": \"QUIC protocol version\",\n \"QUIC_SNI\": \"Server Name Indication domain\",\n \"QUIC_USER_AGENT\": \"User agent string (if available)\",\n \"TIME_FIRST\": \"Timestamp of the first packet\",\n \"TIME_LAST\": \"Timestamp of the last packet\",\n \"DURATION\": \"Duration of the flow in seconds\",\n \"BYTES\": \"Number of transmitted bytes from client to server\",\n \"BYTES_REV\": \"Number of transmitted bytes from server to client\",\n \"PACKETS\": \"Number of packets transmitted from client to server\",\n \"PACKETS_REV\": \"Number of packets transmitted from server to client\",\n \"PPI\": \"Packet metadata sequence (inter-packet times, directions, sizes)\",\n \"PPI_LEN\": \"Number of packets in the PPI sequence\",\n \"PPI_DURATION\": \"Duration of the PPI sequence in seconds\",\n \"PPI_ROUNDTRIPS\": \"Number of roundtrips in the PPI sequence\",\n \"PHIST_SRC_SIZES\": \"Histogram of packet sizes from client to server\",\n \"PHIST_DST_SIZES\": \"Histogram of packet sizes from server to client\",\n \"PHIST_SRC_IPT\": \"Histogram of inter-packet times from client to server\",\n \"PHIST_DST_IPT\": \"Histogram of inter-packet times from server to client\",\n \"APP\": \"Web service label (or background traffic class)\",\n \"CATEGORY\": \"Service category\",\n \"FLOW_ENDREASON_IDLE\": \"Flow was terminated because it was idle\",\n \"FLOW_ENDREASON_ACTIVE\": \"Flow was terminated because it reached the active timeout\",\n \"FLOW_ENDREASON_OTHER\": \"Flow was terminated for other reasons\"}\n "

[dataset_drift_analysis]
description = "not evaluated"

[advanced_metrics]
description = "not evaluated"

[dataset_comparison]
description = "High level comparison from used dataset"
use_case = ""
similar_dataset = ""
# format: id, doi, title, [cited/used,comment/comparison]\n
# format: id, doi, title, [cited/used,comment/comparison]\n
