acronym_info = "Short name of the dataset, which is used as the unique identifier. E.g., CESNET_TLS_Year22"
acronym = "CTU-13"
acronym_aliases_info = "Additional alias for the Dataset Acronym (e.g. CESNET-TLS-Year22-XS). Used to filter the different subsection of the original dataset"
acronym_aliases = "CTU-13"
title_info = "Full title of the dataset. E.g., CESNET-TLS-Year22"
title = ""
paper_title_info = "Full title of the original paper with the dataset"
paper_title = "An Empirical Comparison of Botnet Detection Methods"
authors = "Sebastian Garcia,  Martin Grill,  Jan Stiborek and Alejandro Zunino"
description_info = "High-level description of the dataset. E.g., TLS capture from CESNET2 backbone network over one year (2022). The capture was done using high-speed monitoring probes at the perimeter of CESNET2 network. This dataset provides realistic characteristics of traffic originating from various web browsers, operating systems, mobile devices, desktop machines, and both HTTP/1.1 and HTTP/2 protocols."
description = "The CTU-13 is a dataset of botnet traffic that was captured in the CTU University, Czech Republic, in 2011. The goal of the dataset was to have a large capture of real botnet traffic mixed with normal traffic and background traffic. "
format_info = "Dataset data format. E.g. json, csv, datazoo"
format = "csv"
doi_info = "DOI of this dataset"
doi = "10.1016/j.cose.2014.05.011"
origins_doi_info = "DOI of the original dataset"
origins_doi = ""
submitter = "Dominik Soukup <soukudom@fit.cvut.cz>"
tags_info = "Use tags to categorize the dataset (comma separated)"
tags = "malware"
url = "https://www.stratosphereips.org/datasets-ctu13"
date_submitted = 2025-02-19T21:53:11.665000
files = []
versions = ""
analysis_status = "Requested"
label_name = ""
filename = ""

[collection_workflow]
data_collection_tool = "tcpdump"
data_collection_year = "2011"
feature_extraction_tool_info = "Tool that converts dataset to feature dataset. If any."
feature_extraction_tool = "none"
feature_extraction_tool_description = ""
capture_config_parameters_info = "specific parameters that were used to capture dataset or feature dataset"
capture_config_parameters = ""
real_dataset_info = "Source of the dataset. E.g., real environment, testbed or generated."
real_dataset = ""
annotation_info = "Description of the dataset annotation. E.g., manual, automatic"
annotation = "IP based rules"

[generic_info]
classes = "2"
features = "90"
f1-score_info = "F1-score calculated based on NDVM tool [https://github.com/soukudom/NDVM]"
f1-score = "0.9391318499397754"
performance_metric_info = "Perfomance metric defined by the author. Please define full specification e.g., F1-weighted"
performance_metric_name = ""
performance_metric_value = ""
label_info = "Name of the field with label. In case this is unsupervised dataset, type None"
label = "Label"
key_observations_info = "List of known errors, drifts, limits, ... of the dataset"
key_observations = " * The dataset has 0 small classes, 33700 duplicated sampoles, 0 nan value\n * The dataset is not properly cited based on the author rules\n * The intial paper with this dataset is collected in 2011 but the publication is from 2014\n * Variance in annotation process description in related papers\n * Often used as benchmark dataset\n "
dataset_organization_info = "Structure of the dataset. E.g., per day, per capture, per device"
dataset_organization = ""
dataset_application_info = "Where the dataset has been already applied."
dataset_application = " "
dataset_organization_description = ""
dataset_documentation_info = "How to get started with the dataset. Ideally add example notebook."
dataset_documentation = " "
per_class_data = "{\"Benign\": 75269, \"Malicious\": 7522}"
per_feature_data = "{\"IPT_1\": \"Inter Packet Time 1\", \"IPT_2\": \"Inter Packet Time 2\", \"IPT_3\": \"Inter Packet Time 3\", \"IPT_4\": \"Inter Packet Time 4\", \"IPT_5\": \"Inter Packet Time 5\", \"IPT_6\": \"Inter Packet Time 6\", \"IPT_7\": \"Inter Packet Time 7\", \"IPT_8\": \"Inter Packet Time 8\", \"IPT_9\": \"Inter Packet Time 9\", \"IPT_10\": \"Inter Packet Time 10\", \"IPT_11\": \"Inter Packet Time 11\", \"IPT_12\": \"Inter Packet Time 12\", \"IPT_13\": \"Inter Packet Time 13\", \"IPT_14\": \"Inter Packet Time 14\", \"IPT_15\": \"Inter Packet Time 15\", \"IPT_16\": \"Inter Packet Time 16\", \"IPT_17\": \"Inter Packet Time 17\", \"IPT_18\": \"Inter Packet Time 18\", \"IPT_19\": \"Inter Packet Time 19\", \"IPT_20\": \"Inter Packet Time 20\", \"IPT_21\": \"Inter Packet Time 21\", \"IPT_22\": \"Inter Packet Time 22\", \"IPT_23\": \"Inter Packet Time 23\", \"IPT_24\": \"Inter Packet Time 24\", \"IPT_25\": \"Inter Packet Time 25\", \"IPT_26\": \"Inter Packet Time 26\", \"IPT_27\": \"Inter Packet Time 27\", \"IPT_28\": \"Inter Packet Time 28\", \"IPT_29\": \"Inter Packet Time 29\", \"IPT_30\": \"Inter Packet Time 30\", \"DIR_1\": \"Packet Direction 1\", \"DIR_2\": \"Packet Direction 2\", \"DIR_3\": \"Packet Direction 3\", \"DIR_4\": \"Packet Direction 4\", \"DIR_5\": \"Packet Direction 5\", \"DIR_6\": \"Packet Direction 6\", \"DIR_7\": \"Packet Direction 7\", \"DIR_8\": \"Packet Direction 8\", \"DIR_9\": \"Packet Direction 9\", \"DIR_10\": \"Packet Direction 10\", \"DIR_11\": \"Packet Direction 11\", \"DIR_12\": \"Packet Direction 12\", \"DIR_13\": \"Packet Direction 13\", \"DIR_14\": \"Packet Direction 14\", \"DIR_15\": \"Packet Direction 15\", \"DIR_16\": \"Packet Direction 16\", \"DIR_17\": \"Packet Direction 17\", \"DIR_18\": \"Packet Direction 18\", \"DIR_19\": \"Packet Direction 19\", \"DIR_20\": \"Packet Direction 20\", \"DIR_21\": \"Packet Direction 21\", \"DIR_22\": \"Packet Direction 22\", \"DIR_23\": \"Packet Direction 23\", \"DIR_24\": \"Packet Direction 24\", \"DIR_25\": \"Packet Direction 25\", \"DIR_26\": \"Packet Direction 26\", \"DIR_27\": \"Packet Direction 27\", \"DIR_28\": \"Packet Direction 28\", \"DIR_29\": \"Packet Direction 29\", \"DIR_30\": \"Packet Direction 30\", \"SIZE_1\": \"Packet Size 1\", \"SIZE_2\": \"Packet Size 2\", \"SIZE_3\": \"Packet Size 3\", \"SIZE_4\": \"Packet Size 4\", \"SIZE_5\": \"Packet Size 5\", \"SIZE_6\": \"Packet Size 6\", \"SIZE_7\": \"Packet Size 7\", \"SIZE_8\": \"Packet Size 8\", \"SIZE_9\": \"Packet Size 9\", \"SIZE_10\": \"Packet Size 10\", \"SIZE_11\": \"Packet Size 11\", \"SIZE_12\": \"Packet Size 12\", \"SIZE_13\": \"Packet Size 13\", \"SIZE_14\": \"Packet Size 14\", \"SIZE_15\": \"Packet Size 15\", \"SIZE_16\": \"Packet Size 16\", \"SIZE_17\": \"Packet Size 17\", \"SIZE_18\": \"Packet Size 18\", \"SIZE_19\": \"Packet Size 19\", \"SIZE_20\": \"Packet Size 20\", \"SIZE_21\": \"Packet Size 21\", \"SIZE_22\": \"Packet Size 22\", \"SIZE_23\": \"Packet Size 23\", \"SIZE_24\": \"Packet Size 24\", \"SIZE_25\": \"Packet Size 25\", \"SIZE_26\": \"Packet Size 26\", \"SIZE_27\": \"Packet Size 27\", \"SIZE_28\": \"Packet Size 28\", \"SIZE_29\": \"Packet Size 29\", \"SIZE_30\": \"Packet Size 30\"}"

[dataset_drift_analysis]

[advanced_metrics]
description = ""
perqoda_permutation_slope = "0.502201952684358"
p_value_status = "Mid"
redundancy = "0.3984375"
similarity = "0.5744965505334396"
advanced_metrics_workflow = "dataset-metrics.json"

[dataset_comparison]
description = " "
